pub const DEFAULT_TOKEN_MINT: &str = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"; // USDC MAINNET & DEVNET
pub const DEFAULT_TOKEN_DECIMALS: u8 = 6;
// pub const BONK_TOKEN_MINT: &str = "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"; // BONK MAINNET
pub const BONK_TOKEN_MINT: &str = "BoNKMTTTuHSXBZT6NmctswraMqhRkS6qP7AcTR2SHEkx"; // BONK DEVNET
pub const BONK_PRICE_PER_M: u8 = 30;
